version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/test"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gomod"
    directory: "/swagger-ui-server"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/swagger-ui-server/assets"
    schedule:
      interval: "monthly"
