name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github/workflows
      - uses: docker://rhysd/actionlint:1.6.26
        with:
          args: -color
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make test
